ARG RUBY_VERSION=3.3.5
FROM docker.io/library/ruby:$RUBY_VERSION

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      curl \
      git \
      default-libmysqlclient-dev \
      libyaml-dev \
      nodejs \
      pkg-config \
    && rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV BUNDLE_PATH="/app/vendor/bundle"

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .
